package com.example.ourbook.DataTool.Writer;

import android.content.Context;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;


import com.bumptech.glide.Glide;
import com.example.ourbook.Constants;
import com.example.ourbook.DataTool.BaseUrl;
import com.example.ourbook.DataTool.Book;
import com.example.ourbook.R;

import java.util.List;

// 작성자 화면에 보여질 리사이클러뷰

public class W_BookAdapter extends RecyclerView.Adapter<W_BookAdapter.W_BookViewHolder> {
    private static final String TAG = " W_BookAdapter "+ Constants.AddTAG;
    private List<Book> BookList;
    private OnItemClickListener listener;
    private Context context;




    public W_BookAdapter(Context context ,List<Book> BookList, OnItemClickListener listener) {
        this.BookList = BookList;
        this.listener = listener;
        this.context = context;
    }

    @NonNull
    @Override
    public W_BookViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_w_book, parent, false);
        context = parent.getContext();
        return new W_BookViewHolder(view , context);
    }

    @Override
    public void onBindViewHolder(@NonNull W_BookViewHolder holder, int position) {
        Book book = BookList.get(position);
        holder.bind(book, listener);
    }

    @Override
    public int getItemCount() {
        return BookList.size();
    }

    public static class W_BookViewHolder extends RecyclerView.ViewHolder{
        private TextView bookTitleView;
        private TextView bookInfoView;
        private ImageView bookImageView;
        private  Context context;

        //
        private View itemView; // 이게 맞나..

        public W_BookViewHolder(@NonNull View itemView ,Context context ) {
            super(itemView);
            this.context = context;
            bookTitleView = itemView.findViewById(R.id.book_item_title);
            bookInfoView = itemView.findViewById(R.id.book_item_info);
            bookImageView = itemView.findViewById(R.id.book_item_imageView);
            this.itemView=itemView;
        }

        public void bind(Book book, OnItemClickListener listener) {
            bookTitleView.setText(book.getTitle());
            bookInfoView.setText(book.getBookInfo());
            if(book.getCoverImage()!= null && book.getCoverImage().length()>5) {
                Glide.with(context).load(BaseUrl.BookCoverImage_URL + book.getCoverImage()).into(bookImageView);
            }
//            bookImageView.setImageDrawable(book.getPicture());
            itemView.setOnClickListener(v -> {
                Log.d(TAG, "bind method click listener generated by adapter : ");
                listener.onItemClick(book);
            });
        }
    }
    public interface OnItemClickListener {
        void onItemClick(Book book);

    }
}
